# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - hatespeech-mage-dev

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: https://hatespeechdetector.azurecr.io/
          username: ${{ secrets.AzureAppService_ContainerUsername_29db9b1764a9425d95a438217639f558 }}
          password: ${{ secrets.AzureAppService_ContainerPassword_ff3fcdf3b62940b28fa7d4ceb255e366 }}

      - name: Set up Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose
        env:
          PROJECT_NAME: "hate_speech_detector"
          MAGE_CODE_PATH: "/home/src"
          MAGE_DATABASE_CONNECTION_URL: ${{secrets.MAGE_DATABASE_CONNECTION_URL}}
          PYTHONPATH: "/home/src/hate_speech_detector"

      - name: Build Docker images with Docker Compose
        run: docker-compose -f docker-compose.yml build

      - name: List images
        run: docker images

      - name: Tag and Push mage Docker image
        run: |
          docker tag hate_speech_detector_mage:latest hatespeechdetector.azurecr.io/hatespeech-mage:${{ github.sha }}
          docker push hatespeechdetector.azurecr.io/hatespeech-mage:${{ github.sha }}

      - name: Tag and Push mlflow Docker image
        run: |
          docker tag hate_speech_detector_mlflow:latest  hatespeechdetector.azurecr.io/hatespeech-mlflow:${{ github.sha }}
          docker push hatespeechdetector.azurecr.io/hatespeech-mlflow:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App mage
        id: deploy-to-webapp-mage
        uses: azure/webapps-deploy@v2
        with:
          app-name: "hatespeech-mage-dev"
          slot-name: "production"
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_5674d72a6f7b4b41bf7d229b6c8d80b9 }}
          images: "hatespeechdetector.azurecr.io/hatespeech-mage:${{ github.sha }}"

      - name: Deploy to Azure Web App mlflow
        id: deploy-to-webapp-mlflow
        uses: azure/webapps-deploy@v2
        with:
          app-name: "hatespeech-mlflow"
          slot-name: "production"
          publish-profile: ${{secrets.AzureAppService_PublishProfile_5674d72a6f7b4b41bf7d229b6c8d80b9 }}
          images: "hatespeechdetector.azurecr.io/hatespeech-mlflow:${{ github.sha }}"
